---
title: "Informacje ogólne"
---

## {{< var main.nazwa >}}


Ciekawe książki i strony internetowe zamieszczone zostały w zakładce [książki](/ksiazki). 
Jeśli chciał(a)byś coś dodać prześlij informację przez MS teams.

## Kalendarz

#### Wykład 

1. 21.12.2025
2. 11.01.2025
3. 24.01.2025
4. 25.01.2025
5. 01.02.2026

## Technologie

Uczestnicząc w zajęciach musisz opanować i przynajmniej w podstawowym zakresie posługiwać się następującymi technologiami informatycznymi:

1. Algebra liniowa - wektory, macierze, baza, iloczyn skalarny, iloczyn tensorowy
2. Python, Jupyter notebook, Jupyter lab, Colab
3. Algorytmy sieci neuronowych i uczenia maszynowego w procesie klasyfikacji binarnej

## QPoland 

[QPoland](https://qworld.net/qpoland/) jest cześcią międzynarodowej sieci [QWorld](https://qworld.net).

Zapraszamy do wspólnego poszerzania wiedzy. [Szczegóły](https://qworld.net/join-us/) 
> QWorld is a global network of individuals, groups, and communities collaborating on education and implementation of quantum technologies and research activities.